# this middleware sends the ingress to the oauth container

[http.middlewares]
  [http.middlewares.oauth.forwardAuth]
    address = "http://oauth:4181" # Make sure you have the OAuth service in the traefik stack
    trustForwardHeader = true
    authResponseHeaders = ["X-Forwarded-User"]
